version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"

  node_accident_api:
    image: vfarah/node_accident_api
    depends_on:
      - mongo
    ports:
    -  "9000:9000"

  ng_accident_statistics:
    image: vfarah/ng_accident_statistics
    ports: 
      - "4200:80"
    depends_on:
      - node_accident_api
  
  react_accident_statistics:
    image: vfarah/react_accident_statistics
    ports: 
      - "3000:80"
    depends_on:
      - node_accident_api

  mongo_express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo